- hosts: kubernetes

  become: true

  vars:
    kubernetes_version: '1.32'
    kubernetes_allow_pods_on_control_plane: true
    kubernetes_pod_network:
      cni: 'calico'
      cidr: '192.168.0.0/16'

  pre_tasks: 
    # Ensure br_netfilter module is loaded
    - name: Ensure br_netfilter module is loaded
      ansible.builtin.modprobe:
        name: br_netfilter
        state: present
    
    # Quick fix to ensure bridging is in place
    - name: Ensure bridging is enabled
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes
    - name: Ensure IPv6 bridging is enabled
      ansible.builtin.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present
        reload: yes
    - name: Ensure IP forwarding is enabled
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes

  roles:
    - geerlingguy.containerd

- import_playbook: kubernetes_sigs.kubespray.cluster