- hosts: kubernetes

  become: true

  vars:
    kubernetes_version: '1.32'
    kubernetes_allow_pods_on_control_plane: true
    kubernetes_pod_network:
      cni: 'calico'
      cidr: '192.168.0.0/16'

  pre_tasks: 
    - name: Make sure snap is installed
      apt:
        name: snapd
        state: present
    - name: Install helm using snap
      snap:
        name: helm
        classic: yes
        state: present
    # Ensure br_netfilter module is loaded
    - name: Ensure br_netfilter module is loaded
      modprobe:
        name: br_netfilter
        state: present
    # Quick fix to ensure bridging is in place
    - name: Ensure bridging is enabled
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes
    - name: Ensure IPv6 bridging is enabled
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present
        reload: yes
    - name: Ensure IP forwarding is enabled
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes
    
    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a
    
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    
    - name: Disable firewall
      systemd:
        name: ufw
        state: stopped
        enabled: yes
    
    - name: Check if cgroups are already enabled
      command: cat /boot/firmware/cmdline.txt
      register: cmdline_content
      when:
        - ansible_architecture in ['aarch64', 'armv7l']


    - name: Enable memory and cpuset cgroups
      lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: yes
        regexp: '^(.*)$'
        line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
      when:
        - ansible_architecture in ['aarch64', 'armv7l']


    - name: Reboot the system to apply changes
      reboot:
        msg: "Rebooting to apply cgroup changes"
        reboot_timeout: 300
      when: 
        - ansible_architecture in ['aarch64', 'armv7l']
        - cgroups_update.changed

    - name: Verify cgroups are enabled
      command: cat /proc/cgroups
      register: cgroups_status
      changed_when: false

    - name: Display cgroup status
      debug:
        var: cgroups_status.stdout

  # post_tasks:
  #   - name: Re-enable firewall
  #     systemd:
  #       name: ufw
  #       state: started
  #       enabled: yes
    - name: Allow ports through ufw
      ufw:
        rule: allow
        port: "{{ item }}"
        comment: "Allow {{ item }}"
        state: enabled
      with_items:
        - 22
        - 8080

- import_playbook: kubernetes_sigs.kubespray.cluster